name: deploy to google cloud run

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    name: Cloud Run Deployment
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@master

      - name: Setup GCP Service Account
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Configure Docker
        run: |
          gcloud auth configure-docker

      - name: Create docker repo in Artifact Registry
        run: |
          gcloud artifacts repositories create calendar-docker-repo --repository-format=docker \
          --location=asia-east2 --description="Docker repository"
      
      - name: Build
        run: |
          gcloud builds submit --region=asia-east2 --tag asia-east2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/calendar-docker-repo/calendar-image:latest

      - name: Deploy
        run: |
          gcloud run deploy calendar \
          --region asia-east2 \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/calendar \
          --platform managed \
          --allow-unauthenticated \
          --project ${{ secrets.GCP_PROJECT_ID }}
