on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  migrate:
    name: migrate db
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout 'donutboyy/cardvault'
        uses: actions/checkout@v4

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: pdm install
        run: |
          pip install pdm 
          pdm install

      - name: alembic upgrade head
        run: pdm run alembic upgrade head
